# Generated by Django 3.1.6 on 2021-06-13 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('test_time', models.CharField(default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.test'),
        ),
    ]
