# Generated by Django 3.1.6 on 2021-06-28 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.CharField(max_length=3)),
                ('completed', models.BooleanField(default=False)),
                ('remaining_time', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('test_time', models.CharField(default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answer', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.test')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.test'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.test'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('address1', models.CharField(default='', max_length=500)),
                ('address2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zip', models.CharField(default='', max_length=200)),
                ('profession', models.CharField(default='', max_length=200)),
                ('domain', models.CharField(default='', max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
                ('experience', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
