# Generated by Django 3.1.6 on 2021-07-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
