# Generated by Django 3.1.6 on 2021-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_compulsory',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
