# Generated by Django 3.1.6 on 2021-07-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20210702_0839'),
        ('quizapp', '0004_question_is_compulsory'),
    ]

    operations = [
    ]
