# Generated by Django 3.1.6 on 2021-07-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_merge_20210702_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_compulsory',
        ),
    ]
