# Generated by Django 3.1.6 on 2021-08-02 03:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
