# Generated by Django 3.2.7 on 2021-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer_dashboard', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
